image: gcc

build:
  stage: build
  before_script:
     - apt update
     - apt install -y libgmp3-dev
     - apt install -y libmpfr-dev
     - apt install -y libmpc-dev
     - apt install -y texinfo
     - apt install -y libisl-dev
     - bash ci/toolchain.sh i686-pc-elf > /dev/null

  script:
    - make
  artifacts:
    paths:
      - aurora.bin
  cache:
    paths:
      - "~/cross"

